musicip:
  container_name: "musicip"
  restart: unless-stopped
  image: justifiably/musicip
  ports:
    - 10002:10002
  volumes:
    - /home/core/musicip:/home/musicip
    - /mnt/media/music/:/mnt/media/music:ro
  
